// ==UserScript==
// @name         Camper Wonk.Ink Cat
// @namespace    http://tampermonkey.net/
// @version      3.0
// @author       CAMPER
// @description  Work.ink bypasser
// @match        *://work.ink/*
// @match        *://*.work.ink/*
// @match        *://loot-link.com/s?*
// @match        *://loot-links.com/s?*
// @match        *://lootlink.org/s?*
// @match        *://lootlinks.co/s?*
// @match        *://lootdest.info/s?*
// @match        *://lootdest.org/s?*
// @match        *://lootdest.com/s?*
// @match        *://links-loot.com/s?*
// @match        *://linksloot.net/s?*
// @match        *://rekonise.com/*
// @match        *://link-unlock*
// @match        *://linkvertise.com/*/*
// @match        *://socialwolvez.com/*
// @match        *://scwz.me/*
// @match        *://adfoc.us/*
// @match        *://unlocknow.net/*
// @match        *://sub2get.com/*
// @match        *://sub4unlock.com/*
// @match        *://sub2unlock.net/*
// @match        *://sub2unlock.com/*
// @match        *://mboost.me/*
// @match        *://deltaios-executor.com/ads.html*
// @match        *://rentry.co/*
// @match        *://rekonise.com/*
// @match        *://rkns.link/*
// @match        *://bit.ly/*
// @match        *://rb.gy/*
// @match        *://is.gd/*
// @match        *://rebrand.ly/*
// @match        *://6x.work/*
// @match        *://boost.ink/*
// @match        *://booo.st/*
// @match        *://bst.gg/*
// @match        *://bst.wtf/*
// @match        *://linkunlocker.com/*
// @match        *://unlk.link/*
// @match        *://pandadevelopment.net/getkey*
// @grant        GM_xmlhttpRequest
// @grant        GM.xmlHttpRequest
// @include      *work.ink/*
// @connect      trw.lat
// @connect      abysm.lat
// @run-at       document-start
// @require      https://github.com/Chaaan0917/Camper2.0/raw/refs/heads/main/Camper.js
// @updateURL    https://github.com/Chaaan0917/Camper2.0/raw/refs/heads/main/Main2.0.user.js
// @icon         https://i.kym-cdn.com/entries/icons/original/000/043/403/cover3.jpg
// @grant        none
// ==/UserScript==
